workflows:
    native-android:
        name: Native Android
        instance_type: mac_pro
        environment:
            node: latest
            java: 11
            xcode: 12.2
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
        scripts:

        - echo "single line script"

        - name: Maven Install

          script: maven install

          ignore_failure: true

        - |

          #!/bin/bash/

          brew install maven

          echo "check installed maven version"

          mvn -v

        - name: Install Selenium

          script: install selenium

          ignore_failure: true

        - |

          #!/bin/bash/

          brew install selenium-server
                
        artifacts:
            - app/build/outputs/apk/**/*.apk
            - app/build/outputs/bundle/**/*.aab
        publishing:
            email:
                recipients:
                    - kalgi@nevercode.io
                notify:
                  success: true
                  failure: false
